name: Sync from Bitbucket

on:
  schedule:
    - cron: '0 * * * *' # Sync every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0 # Fetch all history for accurate syncing

      - name: List all files in the GitHub repository after checkout
        run: |
          echo "Listing all files in the GitHub repository after checkout:"
          ls -la

      - name: Debug Bitbucket credentials
        run: |
          echo "BITBUCKET_USERNAME: $BITBUCKET_USERNAME"
          echo "BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD"

      - name: Add Bitbucket remote with git credential helper
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
        run: |
          # Set up Git credential helper to securely store credentials
          git config --global credential.helper store
          echo "https://$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD@bitbucket.org" > ~/.git-credentials
          
          # Add Bitbucket remote and fetch the latest changes
          git remote add bitbucket https://bitbucket.org/solavisetech-migration/aws-etl-tf-python-project.git
          git fetch bitbucket

      - name: List all files after fetching Bitbucket changes
        run: |
          echo "Listing all files after fetching Bitbucket changes:"
          ls -la

      - name: Merge Bitbucket changes
        run: |
          echo "Merging Bitbucket changes into GitHub repository..."
          git merge bitbucket/main --allow-unrelated-histories --no-edit || echo "No changes to merge"

      - name: List all files after merge
        run: |
          echo "Listing all files after merge:"
          ls -la

      - name: Push changes to GitHub
        run: |
          echo "Pushing changes to GitHub..."
          git push origin main

      - name: Clean up
        run: |
          echo "Cleaning up..."
          git remote remove bitbucket
